-- begin PRUEBA1_MATERIA
alter table PRUEBA1_MATERIA add constraint FK_PRUEBA1_MATERIA_ON_ESTUDIANTE foreign key (ESTUDIANTE_ID) references PRUEBA1_ESTUDIANTE(ID)^
create unique index IDX_PRUEBA1_MATERIA_UK_NOMBRE on PRUEBA1_MATERIA (NOMBRE) where DELETE_TS is null ^
create unique index IDX_PRUEBA1_MATERIA_UK_CODIGO on PRUEBA1_MATERIA (CODIGO) where DELETE_TS is null ^
create index IDX_PRUEBA1_MATERIA_ON_ESTUDIANTE on PRUEBA1_MATERIA (ESTUDIANTE_ID)^
-- end PRUEBA1_MATERIA
